service:
  name: big-mouth
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          method: get
          path: /
  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          method: get
          path: /restaurants
    environment:
      defaultResultCount: 10
      restaurantsTable: restaurants
